routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


$var1 = ['except' => 'show'];
$var2 = ['except' => ['show', 'create']];
$var3 = ['only' => ['index', 'edit', 'update']];
$var4 =  ['only' => ['create', 'store', 'destroy']];

Route::resource('users', 'UserController', $var1);

$this->get('/', 'LoginController@showLoginForm')->name('login');
$this->post('/', 'LoginController@login');
$this->post('logout', 'LoginController@logout')->name('logout');

Route::get('current_user', 'UserController@getUser')->name('current_user');
Route::resource('customers', 'CustomerController', $var1);
Route::resource('partners', 'PartnerController', $var1);
Route::resource('support_expiration', 'SupportExpirationController', $var2);
Route::resource('software_versions', 'SoftwareVersionController', $var1);
Route::resource('software_version.compatibility', 'SoftwareVersionCompatibilityController', $var4);
Route::get('device_history/{device}/history', 'DeviceHistoryController@history')->name('device_history.history');
Route::resource('device_configurations', 'DeviceConfigurationController', $var1);

Route::resource('devices', 'DeviceController', $var3);
Route::post('1/device/register', 'DeviceController@register')->name('register');
Route::post('1/update', 'DeviceController@updateDevice')->name('update_device');

Route::get('images/{name}', 'SoftwareVersionController@downloadImage')->name('images');

app/Models/User.php
<?php

namespace App\Models;

use Hash;
use Illuminate\Http\Request;
use Adldap\Laravel\Facades\Adldap;
use Illuminate\Auth\Authenticatable;
use Adldap\Models\User as LdapUser;
use Illuminate\Notifications\Notifiable;
use Kyslik\LaravelFilterable\FilterableTrait;
use App\Http\Resources\User as UserResource;
use App\Http\Resources\UserList;
use App\Filters\User as UserFilter;
use App\Models\Traits\ShowEntity;
use App\Models\Traits\SaveEntity;
use App\Models\Traits\DestroyEntity;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;

class User extends BaseModel implements AuthenticatableContract
{
    use Notifiable,
        ShowEntity,
        SaveEntity,
        DestroyEntity,
        Authenticatable,
        FilterableTrait;

    /**
     * Table name
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * Validating rules
     *
     * @var array
     */
    protected $rules = [
        'name'  =>  'required|unique:users|min:1|max:35',
        'email' => 'email|max:255|unique:users',
        'password' => 'required|min:1|max:255',
        'ldap' => 'required|boolean',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'ldap',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Hash password before save
     *
     * @param string $pass password
     *
     * @return void
     */
    public function setPasswordAttribute($pass)
    {
        $this->attributes['password'] = Hash::make($pass);
        if (is_null($pass)) {
            unset($this->attributes['password']);
        }
    }

    /**
     * Attempt login LDAP user
     *
     * @param Request $request request
     *
     * @return bool
     */
    public static function attemptLdapUser(Request $request)
    {
        $result = false;
        $params = $request->all();
        $name = array_get($params, 'name');
        $password = array_get($params, 'password');
        if (Adldap::auth()->attempt($name, $password)
            and ($ldapUser = self::getLdapUser($name, $password))
        ) {
            self::createUpdateLdapUser($ldapUser, $password);
            $result = true;
        }
        return $result;
    }

    /**
     * Create or update, if exists, ldap user in local database
     *
     * @param LdapUser $ldapUser ldap User
     * @param string   $password password
     *
     * @return void
     */
    protected static function createUpdateLdapUser(LdapUser $ldapUser, $password)
    {
        $dbUser = User::firstOrNew(
            ['name' => strtolower($ldapUser->getAccountName())],
            ['ldap' => true]
        );
        $dbUser->fill(
            [
                'email' => $ldapUser->getEmail(),
                'password' => $password
            ]
        );
        $dbUser->save();
    }

    /**
     * Return Ldap user if exists and is in group Sirwisa-overlord or return null
     *
     * @param string $name     name
     * @param string $password password
     *
     * @return mixed
     */
    protected static function getLdapUser($name, $password)
    {
        Adldap::auth()->bind($name, $password);
        $user = Adldap::search()->find($name);
        return $user->inGroup('Sirwisa-overlord') ? $user : null;
    }

    /**
     * Get all of the models from the database.
     *
     * @param UserFilter $filters filters
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function collectionItems(UserFilter $filters)
    {
        $items = self::filter($filters)->get();
        return UserList::collection($items);
    }

    /**
     * Return resource item data
     *
     * @param string $id id
     *
     * @return array
     */
    public function editItem($id)
    {
        $res = new UserResource($this->find($id));
        return $res->toArray(0);
    }

    /**
     * Return resource item data
     *
     * @return array
     */
    public function createItem()
    {
        $res = new UserResource(new self());
        return $res->toArray(0);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Filters\User as UserFilter;
use App\Http\Controllers\Traits\Show;
use App\Http\Controllers\Traits\Edit;
use App\Http\Controllers\Traits\Store;
use App\Http\Controllers\Traits\Create;
use App\Http\Controllers\Traits\Update;
use App\Http\Controllers\Traits\Destroy;

class UserController extends AdminController
{
    use Show,
        Edit,
        Store,
        Create,
        Update,
        Destroy;

    protected $model;

    /**
     * Where to redirect users after login.
     *
     * @var string
     */
    protected $redirectTo = '/users';

    /**
     * UserController constructor.
     *
     * @param User $model Users model
     */
    public function __construct(User $model)
    {
        parent::__construct();
        $this->model = $model;
    }

    /**
     * Display a listing of the resource.
     *
     * @param UserFilter $filters filters
     *
     * @return \Illuminate\Http\Response
     */
    public function index(UserFilter $filters)
    {
        return view($this->model->getTable() . '.index', ['data' => $this->model->collectionItems($filters)]);
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')
@section('title', _i('Create user'))
@section('content')
    {{ Form::open(['route' => 'users.store']) }}
    @include('users.form_fields')
    {{ Form::close() }}
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')
@section('title', _i('Update user'))
@section('content')
    {{ Form::model(array_get($data, 'resource'), ['route' => ['users.update', array_get($data, 'id')], 'method' => 'put']) }}
    @include('users.form_fields')
    {{ Form::close() }}
@endsection

resources/views/users/form_fields.blade.php
{{ Form::bsFields(
    [
        'name' => ['text' => [_i('User name')]],
        'email' => ['email' => [_i('E-mail address')]],
        'password' => ['password' => [_i('Password')]],
        'ldap' => ['checkbox' => [_i('LDAP')]],
        'submit' => ['submit' => [_i('Submit')]],
    ]
) }}

resources/views/users/index.blade.php
@extends('layouts.app')
@section('title', _i('Users list'))
@section('list_buttons')
    <a href="{{ route('users.create') }}">{{ _i('Create') }}</a>
@endsection
@section('content')
    {{ Html::bsList($data, [
        'name' => [_i('User name'), true],
        'email' => [_i('E-mail address'), true],
        'ldap' => [_i('LDAP'), true],
    ]) }}
@endsection

resources/views/users/login.blade.php
@extends('welcome')
@section('title', _i('Login form'))
@section('content')
    <div class="text-center mb-4">
        <h1 class="h3 mb-3 font-weight-normal">Overlord</h1>
    </div>
    {{ Form::open(['route' => 'login', 'class' => 'form-signin']) }}
        {{ Form::bsFields(
            [
                'name' => ['text' => [_i('User name')]],
                'password' => ['password' => [_i('Password')]],
                'remember' => ['checkbox' => [_i('Remember me')]],
                'submit' => ['submit' => [_i('Submit')]],
            ]
        ) }}
    {{ Form::close() }}
@endsection