routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


$var1 = ['except' => 'show'];
$var2 = ['except' => ['show', 'create']];
$var3 = ['only' => ['index', 'edit', 'update']];
$var4 =  ['only' => ['create', 'store', 'destroy']];

Route::resource('users', 'UserController', $var1);

$this->get('/', 'LoginController@showLoginForm')->name('login');
$this->post('/', 'LoginController@login');
$this->post('logout', 'LoginController@logout')->name('logout');

Route::get('current_user', 'UserController@getUser')->name('current_user');
Route::resource('customers', 'CustomerController', $var1);
Route::resource('partners', 'PartnerController', $var1);
Route::resource('support_expiration', 'SupportExpirationController', $var2);
Route::resource('software_versions', 'SoftwareVersionController', $var1);
Route::resource('software_version.compatibility', 'SoftwareVersionCompatibilityController', $var4);
Route::get('device_history/{device}/history', 'DeviceHistoryController@history')->name('device_history.history');
Route::resource('device_configurations', 'DeviceConfigurationController', $var1);

Route::resource('devices', 'DeviceController', $var3);
Route::post('1/device/register', 'DeviceController@register')->name('register');
Route::post('1/update', 'DeviceController@updateDevice')->name('update_device');

Route::get('images/{name}', 'SoftwareVersionController@downloadImage')->name('images');

app/Models/Partner.php
<?php

namespace App\Models;

use App\Models\Traits\ShowEntity;
use App\Models\Traits\SaveEntity;
use App\Models\Traits\DestroyEntity;
use Kyslik\LaravelFilterable\FilterableTrait;
use App\Http\Resources\Partner as PartnerResource;
use App\Http\Resources\PartnerList;
use App\Filters\Partner as PartnerFilter;

class Partner extends BaseModel
{
    use ShowEntity,
        SaveEntity,
        DestroyEntity,
        FilterableTrait;

    /**
     * Table name
     *
     * @var string
     */
    protected $table = 'partners';

    /**
     * Validating rules
     *
     * @var array
     */
    protected $rules = [
        'country_id' => 'required|integer|exists:countries,id',
        'name'  =>  'required|unique:software_components|min:1|max:45',
        'type'  =>  'required|min:1|max:45',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'country_id',
        'name',
        'type',
    ];

    /**
     * Get all of the models from the database.
     *
     * @param PartnerFilter $filters filters
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function collectionItems(PartnerFilter $filters)
    {
        $items = self::filter($filters)->get();
        return PartnerList::collection($items);
    }

    /**
     * Return resource item data
     *
     * @param string $id id
     *
     * @return array
     */
    public function editItem($id)
    {
        $res = new PartnerResource($this->find($id));
        return $res->toArray(0);
    }

    /**
     * Return resource item data
     *
     * @return array
     */
    public function createItem()
    {
        $res = new PartnerResource(new self());
        return $res->toArray(0);
    }

    /**
     * Define BelongsTo relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function country()
    {
        return $this->belongsTo(Country::class);
    }
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use Validator;
use App\Models\Partner;
use App\Filters\Partner as PartnerFilter;
use App\Http\Controllers\Traits\Show;
use App\Http\Controllers\Traits\Edit;
use App\Http\Controllers\Traits\Store;
use App\Http\Controllers\Traits\Create;
use App\Http\Controllers\Traits\Update;
use App\Http\Controllers\Traits\Destroy;

class PartnerController extends AdminController
{
    use Show,
        Edit,
        Store,
        Create,
        Update,
        Destroy;

    protected $model;

    /**
     * PartnerController constructor.
     *
     * @param Partner $model Partner model
     */
    public function __construct(Partner $model)
    {
        parent::__construct();
        $this->model = $model;
    }

    /**
     * Display a listing of the resource.
     *
     * @param PartnerFilter $filters filters
     *
     * @return \Illuminate\Http\Response
     */
    public function index(PartnerFilter $filters)
    {
        return view($this->model->getTable() . '.index', ['data' => $this->model->collectionItems($filters)]);
    }
}

resources/views/partners/create.blade.php
@extends('layouts.app')
@section('title', _i('Create partner'))
@section('content')
    {{ Form::open(['route' => 'partners.store']) }}
    @include('partners.form_fields')
    {{ Form::close() }}
@endsection

resources/views/partners/edit.blade.php
@extends('layouts.app')
@section('title', _i('Update partner'))
@section('content')
    {{ Form::model(array_get($data, 'resource'), ['route' => ['partners.update', array_get($data, 'id')], 'method' => 'put']) }}
    @include('partners.form_fields')
    {{ Form::close() }}
@endsection

resources/views/partners/form_fields.blade.php
{{ Form::bsFields(
    [
        'name' => ['text' => [_i('Partner name')]],
        'country_id' => [
            'select' => [
                _i('Country'),
                array_get($data, 'countries'),
                array_get($data, 'country_id'),
            ]
        ],
        'type' => ['text' => [_i('Type')]],
        'submit' => ['submit' => [_i('Submit')]],
    ]
) }}

resources/views/partners/index.blade.php
@extends('layouts.app')
@section('title', _i('Partners list'))
@section('list_buttons')
    <a href="{{ route('partners.create') }}">{{ _i('Create') }}</a>
@endsection
@section('content')
    {{ Html::bsList($data,
    [
        'name' => [_i('Partner name'), true],
        'country' => [_i('Country'), true],
        'type' => [_i('Type'), true],
    ]) }}
@endsection