routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


$var1 = ['except' => 'show'];
$var2 = ['except' => ['show', 'create']];
$var3 = ['only' => ['index', 'edit', 'update']];
$var4 =  ['only' => ['create', 'store', 'destroy']];

Route::resource('users', 'UserController', $var1);

$this->get('/', 'LoginController@showLoginForm')->name('login');
$this->post('/', 'LoginController@login');
$this->post('logout', 'LoginController@logout')->name('logout');

Route::get('current_user', 'UserController@getUser')->name('current_user');
Route::resource('customers', 'CustomerController', $var1);
Route::resource('partners', 'PartnerController', $var1);
Route::resource('support_expiration', 'SupportExpirationController', $var2);
Route::resource('software_versions', 'SoftwareVersionController', $var1);
Route::resource('software_version.compatibility', 'SoftwareVersionCompatibilityController', $var4);
Route::get('device_history/{device}/history', 'DeviceHistoryController@history')->name('device_history.history');
Route::resource('device_configurations', 'DeviceConfigurationController', $var1);

Route::resource('devices', 'DeviceController', $var3);
Route::post('1/device/register', 'DeviceController@register')->name('register');
Route::post('1/update', 'DeviceController@updateDevice')->name('update_device');

Route::get('images/{name}', 'SoftwareVersionController@downloadImage')->name('images');

app/Models/DeviceConfiguration.php
<?php

namespace App\Models;

use Illuminate\Http\Request;
use App\Models\Traits\ShowEntity;
use App\Models\Traits\SaveEntity;
use App\Models\Traits\DestroyEntity;
use Kyslik\LaravelFilterable\FilterableTrait;
use App\Http\Resources\DeviceConfiguration as DeviceConfigurationResource;
use App\Http\Resources\DeviceConfigurationList;
use App\Filters\DeviceConfiguration as DeviceConfigurationFilter;

class DeviceConfiguration extends BaseModel
{
    use ShowEntity,
        SaveEntity,
        DestroyEntity,
        FilterableTrait;

    /**
     * Table name
     *
     * @var string
     */
    protected $table = 'device_configurations';

    /**
     * Validating rules
     *
     * @var array
     */
    protected $rules = [
        'device_id' => 'required|integer|exists:devices,id',
        'mgmt_ip' => 'max:45',
        'mgmt_login' => 'max:45',
        'mgmt_password' => 'max:45',
        'ip' => 'max:45',
        'system_login' => 'max:45',
        'system_password' => 'max:45',
        'bios_password' => 'max:45',
        'has_mgmt' => 'required|boolean',
        'has_access' => 'required|boolean',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'device_id',
        'mgmt_ip',
        'mgmt_login',
        'mgmt_password',
        'ip',
        'system_login',
        'system_password',
        'bios_password',
        'has_mgmt',
        'has_access',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'mgmt_password',
        'system_password',
        'bios_password',
    ];

    /**
     * Get all of the models from the database.
     *
     * @param DeviceConfigurationFilter $filters filters
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function collectionItems(DeviceConfigurationFilter $filters)
    {
        $items = self::with(
            [
                'device',
            ]
        )->filter($filters)->get();
        return DeviceConfigurationList::collection($items);
    }

    /**
     * Define BelongsTo relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function device()
    {
        return $this->belongsTo(Device::class);
    }

    /**
     * Return resource item data
     *
     * @param Request $request request
     * @param string  $id      id
     *
     * @return array
     */
    public function editItem(Request $request, $id)
    {
        $res = new DeviceConfigurationResource($this->find($id));
        return $res->toArray($request);
    }

    /**
     * Return resource item data
     *
     * @return array
     */
    public function createItem()
    {
        $res = new DeviceConfigurationResource(new self());
        return $res->toArray(0);
    }
}

app/Http/Controllers/DeviceConfigurationController.php
<?php

namespace App\Http\Controllers;

use Validator;
use Illuminate\Http\Request;
use App\Http\Controllers\Traits\Store;
use App\Http\Controllers\Traits\Create;
use App\Http\Controllers\Traits\Update;
use App\Http\Controllers\Traits\Destroy;
use App\Models\DeviceConfiguration;
use App\Filters\DeviceConfiguration as DeviceConfigurationFilter;

class DeviceConfigurationController extends AdminController
{
    use Store,
        Create,
        Update,
        Destroy;

    protected $model;

    /**
     * DeviceConfigurationController constructor.
     *
     * @param DeviceConfiguration $model Customer model
     */
    public function __construct(DeviceConfiguration $model)
    {
        parent::__construct();
        $this->model = $model;
    }

    /**
     * Display a listing of the resource.
     *
     * @param DeviceConfigurationFilter $filters filters
     *
     * @return \Illuminate\Http\Response
     */
    public function index(DeviceConfigurationFilter $filters)
    {
        return view($this->model->getTable() . '.index', ['data' => $this->model->collectionItems($filters)]);
    }

    /**
     * Display edit page
     *
     * @param Request $request request
     * @param string  $id      id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        return view($this->model->getTable() . '.edit', ['data' => $this->model->editItem($request, $id)]);
    }
}

resources/views/device_configurations/create.blade.php
@extends('layouts.app')
@section('title', _i('Create device configuration'))
@section('content')
    {{ Form::open(['route' => 'device_configurations.store']) }}
    @include('device_configurations.form_fields')
    {{ Form::close() }}
@endsection

resources/views/device_configurations/edit.blade.php
@extends('layouts.app')
@section('title', _i('Update device configuration'))
@section('content')
    {{ Form::model(array_get($data, 'resource'), ['route' => ['device_configurations.update', array_get($data, 'id')], 'method' => 'put']) }}
    @include('device_configurations.form_fields')
    {{ Form::close() }}
@endsection

resources/views/device_configurations/form_fields.blade.php
{{ Form::bsFields(
    [
        'device_id' => [
            'select' => [
                _i('Device'),
                array_get($data, 'devices'),
                array_get($data, 'device_id'),
            ]
        ],
        'mgmt_ip' => ['text' => [_i('MGMT IP')]],
        'mgmt_login' => ['text' => [_i('MGMT login')]],
        'mgmt_password' => [array_get($data, 'password_input') => [_i('MGMT password')]],
        'ip' => ['text' => [_i('IP')]],
        'system_login' => ['text' => [_i('System login')]],
        'system_password' => [array_get($data, 'password_input') => [_i('System password')]],
        'bios_password' => [array_get($data, 'password_input') => [_i('BIOS password')]],
        'has_mgmt' => ['checkbox' => [_i('Has MGMT')]],
        'has_access' => ['checkbox' => [_i('Has access')]],
        'submit' => ['submit' => [_i('Submit')]],
    ]
) }}

resources/views/device_configurations/index.blade.php
@extends('layouts.app')
@section('title', _i('Device configuration list'))
@section('list_buttons')
    <a href="{{ route('device_configurations.create') }}">{{ _i('Create') }}</a>
@endsection
@section('content')
    {{ Html::bsList($data,
    [
        'device' => [_i('Device serial'), true],
        'mgmt_ip' => [_i('MGMT ip'), true],
        'mgmt_login' => [_i('MGMT login'), true],
        'ip' => [_i('IP'), true],
        'system_login' => [_i('System login'), true],
        'has_mgmt' => [_i('Has MGMT'), true],
        'has_access' => [_i('Has access'), true],
    ]) }}
@endsection