routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


$var1 = ['except' => 'show'];
$var2 = ['except' => ['show', 'create']];
$var3 = ['only' => ['index', 'edit', 'update']];
$var4 =  ['only' => ['create', 'store', 'destroy']];

Route::resource('users', 'UserController', $var1);

$this->get('/', 'LoginController@showLoginForm')->name('login');
$this->post('/', 'LoginController@login');
$this->post('logout', 'LoginController@logout')->name('logout');

Route::get('current_user', 'UserController@getUser')->name('current_user');
Route::resource('customers', 'CustomerController', $var1);
Route::resource('partners', 'PartnerController', $var1);
Route::resource('support_expiration', 'SupportExpirationController', $var2);
Route::resource('software_versions', 'SoftwareVersionController', $var1);
Route::resource('software_version.compatibility', 'SoftwareVersionCompatibilityController', $var4);
Route::get('device_history/{device}/history', 'DeviceHistoryController@history')->name('device_history.history');
Route::resource('device_configurations', 'DeviceConfigurationController', $var1);

Route::resource('devices', 'DeviceController', $var3);
Route::post('1/device/register', 'DeviceController@register')->name('register');
Route::post('1/update', 'DeviceController@updateDevice')->name('update_device');

Route::get('images/{name}', 'SoftwareVersionController@downloadImage')->name('images');

app/Models/SoftwareVersion.php
<?php

namespace App\Models;

use Config;
use App\Models\Services\VersionService;
use Kyslik\LaravelFilterable\FilterableTrait;
use App\Models\Traits\DestroyEntity;
use App\Models\Traits\SaveEntityRelations;
use App\Filters\SoftwareVersion as SoftwareVersionFilter;
use App\Http\Resources\SoftwareVersionList;
use App\Http\Resources\SoftwareVersion as SoftwareVersionResource;

class SoftwareVersion extends BaseModel
{
    use DestroyEntity,
        FilterableTrait,
        SaveEntityRelations;

    /**
     * Boot function from laravel.
     *
     * @return mixed
     */
    protected static function boot()
    {
        parent::boot();

        static::saving(
            function ($model) {
                $fileName = self::getImagePath($model->file_name);
                $model->checksum = hash_file('sha256', $fileName);
            }
        );
    }

    /**
     * Table name
     *
     * @var string
     */
    protected $table = 'software_versions';

    /**
     * Validating rules
     *
     * @var array
     */
    protected $rules = [
        'software_branch_id' => 'required|integer|exists:software_branches,id',
        'software_component_id' => 'required|integer|exists:software_components,id',
        'version'  => 'required|min:5|max:45',
        'file_name'  => 'required|string|image_exists|min:5|max:120',
        'is_enabled' => 'required|boolean',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'software_branch_id',
        'software_component_id',
        'version',
        'file_name',
        'is_enabled',
    ];

    /**
     * Array of references
     *
     * @var array
     */
    protected $references = [
        'platforms',
    ];

    /**
     * Encode version attribute to db format
     *
     * @param string $version password
     *
     * @return void
     */
    public function setVersionAttribute($version)
    {
        $this->attributes['version'] = VersionService::encode($version);
    }

    /**
     * Decode version attribute to short format
     *
     * @param string $version password
     *
     * @return string
     */
    public function getVersionAttribute($version)
    {
        return VersionService::trim($version);
    }

    /**
     * Return version image file path
     *
     * @param string $fileName file name
     *
     * @return string
     */
    public static function getImagePath($fileName)
    {
        $imagesPath = Config::get('constants.VERSION_IMAGES_PATH');
        return $imagesPath . DIRECTORY_SEPARATOR . $fileName;
    }

    /**
     * Return version image file url
     *
     * @param string $fileName file name
     *
     * @return string
     */
    public static function getImageUrl($fileName)
    {
        return url('images/' . $fileName);
    }

    /**
     * Return response download image file
     *
     * @param string $name image name
     *
     * @return array
     */
    public function downloadImage($name)
    {
        $path = self::getImagePath($name);
        return response()->download($path, $name);
    }

    /**
     * Get all of the models from the database.
     *
     * @param SoftwareVersionFilter $filters filters
     *
     * @return \Illuminate\Http\Resources\Json\AnonymousResourceCollection
     */
    public function collectionItems(SoftwareVersionFilter $filters)
    {
        $items = self::with(
            [
                'softwareBranch',
                'softwareComponent',
                'platforms',
            ]
        )->filter($filters)->get();
        //dd($items);
        return SoftwareVersionList::collection($items);
    }

    /**
     * Return resource item data
     *
     * @param string $id id
     *
     * @return array
     */
    public function editItem($id)
    {
        $res = new SoftwareVersionResource($this->find($id));
        return $res->toArray(0);
    }

    /**
     * Return resource item data
     *
     * @return array
     */
    public function createItem()
    {
        $res = new SoftwareVersionResource(new self());
        return $res->toArray(0);
    }

    /**
     * Define BelongsToMany relation to Platform
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function platforms()
    {
        return $this->belongsToMany(Platform::class);
    }

    /**
     * Define BelongsTo relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function softwareBranch()
    {
        return $this->belongsTo(SoftwareBranch::class);
    }

    /**
     * Define BelongsTo relation
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function softwareComponent()
    {
        return $this->belongsTo(SoftwareComponent::class);
    }

}

app/Http/Controllers/SoftwareVersionController.php
<?php

namespace App\Http\Controllers;

use Validator;
use App\Models\SoftwareVersion;
use App\Http\Controllers\Traits\Show;
use App\Http\Controllers\Traits\Edit;
use App\Http\Controllers\Traits\Store;
use App\Http\Controllers\Traits\Create;
use App\Http\Controllers\Traits\Update;
use App\Http\Controllers\Traits\Destroy;
use App\Filters\SoftwareVersion as SoftwareVersionFilter;

class SoftwareVersionController extends AdminController
{
    use Show,
        Edit,
        Store,
        Create,
        Update,
        Destroy;

    protected $model;

    /**
     * SoftwareVersionController constructor.
     *
     * @param SoftwareVersion $model SoftwareVersion model
     */
    public function __construct(SoftwareVersion $model)
    {
        parent::__construct();
        $this->model = $model;
    }

    /**
     * Display a listing of the resource.
     *
     * @param SoftwareVersionFilter $filters filters
     *
     * @return \Illuminate\Http\Response
     */
    public function index(SoftwareVersionFilter $filters)
    {
        return view($this->model->getTable() . '.index', ['data' => $this->model->collectionItems($filters)]);
    }

    /**
     * Return response download image file
     *
     * @param string $name image name
     *
     * @return array
     */
    public function downloadImage($name)
    {
        return $this->model->downloadImage($name);
    }
}

resources/views/software_versions/create.blade.php
@extends('layouts.app')
@section('title', _i('Create software version'))
@section('content')
    {{ Form::open(['route' => 'software_versions.store']) }}
    @include('software_versions.form_fields')
    {{ Form::close() }}
@endsection

resources/views/software_versions/edit.blade.php
@extends('layouts.app')
@section('title', _i('Update software version'))
@section('content')
    {{ Form::model(array_get($data, 'resource'), ['route' => ['software_versions.update', array_get($data, 'id')], 'method' => 'put']) }}
    @include('software_versions.form_fields')
    {{ Form::close() }}
    @include('software_version_compatibility.index')
@endsection

resources/views/software_versions/form_fields.blade.php
@php($aParams = !is_null(array_get($data, 'id')) ? ['disabled' => 'disabled'] : [])

{{ Form::bsFields(
    [
        'version' => ['text' => [_i('Software version'), $aParams]],
        'file_name' => ['text' => [_i('File name'), $aParams]],
        'software_component_id' => [
            'select' => [
                _i('Software component'),
                array_get($data, 'software_components'),
                array_get($data, 'software_component_id'),
                $aParams
            ]
        ],
        'software_branch_id' => [
            'select' => [
                _i('Software branch'),
                array_get($data, 'software_branches'),
                array_get($data, 'software_branch_id'),
            ]
        ],
        'platforms[]' => [
            'select' => [
                _i('Platforms'),
                array_get($data, 'platforms'),
                array_get($data, 'platform_ids'),
            ]
        ],
        'is_enabled' => ['checkbox' => [_i('Is enabled')]],
        'submit' => ['submit' => [_i('Submit')]],
    ]
) }}

resources/views/software_versions/index.blade.php
@extends('layouts.app')
@section('title', _i('Software versions list'))
@section('list_buttons')
    <a href="{{ route('software_versions.create') }}">{{ _i('Create') }}</a>
@endsection
@section('content')
    {{ Html::bsList($data, [
        'version' => [_i('Software version'), true],
        'file_name' => [_i('File name'), true],
        'software_component' => [_i('Software component'), true],
        'software_branch' => [_i('Software branch'), true],
        'platforms' => [_i('Platforms'), true],
        'is_enabled' => [_i('Is enabled'), true],
    ]) }}
@endsection